import { Inter } from 'next/font/google';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import PrelineScript from './components/PrelineScript';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

config.autoAddCss = false;
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Bio Express',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                {children}
                <ToastContainer />
                <PrelineScript />
            </body>
        </html>
    );
}
