import { Inter } from 'next/font/google';
import '../globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import PrelineScript from '../components/PrelineScript';

import Nav from '../components/Nav';
config.autoAddCss = false;
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <>
            <>
                <Nav />
            </>

            <>{children}</>

            <PrelineScript />
        </>
    );
}
